; PlatformIO Project Configuration
; STM32F103C8T6 (Blue Pill) - LCD 8-bit parallel LCD + TouchScreen

[env:bluepill_f103c8_128k]
platform = ststm32
board = bluepill_f103c8_128k
framework = arduino
board_build.f_cpu = 72000000L
upload_protocol = stlink
debug_tool = stlink
:monitor_port = COM7
monitor_speed = 115200

board_upload.maximum_size = 131072
;build_unflags = -flto
build_flags =
    -ffast-math
    -flto 
    ;-Ofast
    ;-O3
    ;-Wl,--gc-sections  ; It reduces the size by discarding unused code.
    ;-Wl,--print-gc-sections ; Hangi fonksiyonların silindiğini terminalde görmek için (isteğe bağlı)
    ;-fdata-sections
    ;-Wno-builtin-macro-redefined



